name: 'Emoji reactions bot'

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  emoji:
    runs-on: ubuntu-latest
    steps:
      - name: React to new issues
        if: github.event_name == 'issues'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.reactions.createForReaction(context.repo.owner, context.repo.repo, context.payload.issue.id, '🎉');
      
      - name: React to new PRs
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.reactions.createForReaction(context.repo.owner, context.repo.repo, context.payload.pull_request.id, '🚀');