name: 'Welcome first-time contributors'

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Welcome new contributors
        uses: actions-cool/maintainer-validate@v1
        with:
          GITHUB_TOKEN: ${{ github.token }}
          welcome-message: "🎉 Welcome to S3RLinux! Thanks for the PR! RAVE ALL NIGHT 💀"
          issue-labels: "welcome"
          pr-labels: "ready-for-review"
          closed-pr-message: "Thanks for contributing to S3RLinux! 💜"
